# Generated by Django 3.2.9 on 2021-12-14 13:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0002_rename_image_imagecollage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageCollage',
            new_name='ImageCollageModel',
        ),
    ]
